### ISSUE TITLE
New line following algorithms.

### ISSUE THREAD

**Issue by AhmedSamara** [IEEERobotics/bot2014#132]
New ideas for approaching line following:

-The IR arrays can be assigned a Cartesian co-ordinates (assuming, the bottom left corner is (0,0)). The location of the line can be easily calculated in terms of both distances and indexes by measuring the distances between sensors.

Whenever the bot is on top of a line, there will be two globs of "on" IR's, and from there a heading can be easily calculated using basic Cartesian plane geometry, and a heading can be calculated.

(ie: IRs (15,15) and (1,0) are lit up, we can see how far off the bot is, and what the correct angle heading is.

![image](https://cloud.githubusercontent.com/assets/2405319/3308846/a26299ae-f68b-11e3-826e-7655bc6299e1.png)

It's worth noting that the actual shape of the line under the robot doesn't matter. We can use those two points to treat any curve the exact same way we would any other straight line.

**Comment by jasteve4** [comment]
We are able to follow the line with some degree of error.
