### ISSUE TITLE
[Python developer] Implement etch-a-sketch Code.

### ISSUE THREAD

**Issue by AhmedSamara** [IEEERobotics/bot2014#147]
This is a more challenging task, but I think it's one that's well defined, and can be worked on independently because it doesn't rely on sensing and outside hardware beyond the two stepper motors that it will control, and there are some solid [example projects](http://patrickmccabemakes.com/hardware/da_Vinci/) that are worth looking at.

**Comment by AhmedSamara** [comment]
@psychomugs has a working IEEE drawer on an Arduino.

I am somewhat ok with just connecting the Arduino to the beaglebone serially and having the beaglebone tell it when to start drawing and respond when it's done.

**Comment by AhmedSamara** [comment]
https://gist.github.com/psychomugs/9c8de043fff13a6e508a

**Comment by AhmedSamara** [comment]
@ChadZhongqiangChen 

This still needs to be ported to Python, although I'm still considering doing the ugly but effective method of just strapping on the Arduino and having that solve the problem.

You'll need to use the hardware/stepper_motor.py abstraction.

**Comment by jasteve4** [comment]
This will be solved and not need when the new cape is created.
