### ISSUE TITLE
ADC cap redesign connector search

### ISSUE THREAD

**Issue by jasteve4** [IEEERobotics/bot2014#153]
I have looked as hard as can, and there is just no connector that meets the pitch (1.25 mm) requirement that I need. So, I am open to suggestions and help in finding a connector, any thing bigger and it will not fit on a cap design. Every thing that I am seeing requires crimp connections. Maybe we can revisit this discussion on Tuesdays meeting.

**Comment by jakunesh** [comment]
Long solved, version 1 of the ADC cape is on the bot and working
