### ISSUE TITLE
New Wheel Attachment 

### ISSUE THREAD

**Issue by cdyoder** [IEEERobotics/bot2014#169]
For both the Omni wheels and the new Mecanum wheels, there is a square, 0.125" x 0.125" hole in the center of each wheel. For all motors currently in the possession of the club, the drive shafts are either round or D shafts. An adaption technique/connection needs to be made between the two.

James was looking into this somewhat Friday. Mark also proposed a solution to this problem; however, I am not aware of the status of either solution. Anyone interested in working on this problem who cannot find James or Mark for consult can see me (C. D. Yoder) for further information. This is higher priority due to the need to mount the new wheels on the motors so we can validate that the new mecanum wheels will still drive properly (and then adjust code accordingly). 

-C. D. Yoder

**Comment by AhmedSamara** [comment]
Is this still an issue?

**Comment by SeanKetring** [comment]
It is an issue, but it is not a priority. Here is a link to an old solution we simply failed to implement well. It is printing now:

http://www.thingiverse.com/thing:230816/#files

Once it prints, we can place it on the bot and see how it behaves. If successful, we can print three more.

**Comment by jakunesh** [comment]
I've gotten one hub printed. It is a good print, the problem is that these hubs have a hollow inside, so that doesn't print as nicely.

I've placed it in the current work box for evaluation Thursday

**Comment by jakunesh** [comment]
This is becoming a more and more annoying issue for the CS bot, is is slowing development of line following.  It needs to be bumped up in priority

**Comment by jakunesh** [comment]
For the sake of time we gave up on finding an elegant solution and @cdyoder glued the hubs to the shaft. Wheels haven't fallen off yet, despite some pretty abusive driving recently.
