### ISSUE TITLE
2015 start signal detect.

### ISSUE THREAD

**Issue by AhmedSamara** [IEEERobotics/bot2014#173]
The start signal this year is provided by a red LED that starts out on, and then turns off to signal the beginning of the round.

color_sensor.py is reusable for the most part, but there are some changes that will be needed to make it relevant again.

We just need to get it so that we have a function that looks at a color, and waits for it to go away before ending.

Some features we need/want and things to think about in terms of what to implement:

-The color sensor works by returning values for Red, green, and blue.

-For some reason, red is just naturally dominant in what the color sensor sees, regardless of what it's looking at (problem last year, but good for us now).

-In the past, we waited for an LED to turn on to signal the start. This time it's an LED turning off. So the loop will just be looking at the opposite of what we did before.

-We want an LED somewhere to light up when it's viewing red, to help us with lining up the bot in the start location on top of the start signal.

-In the past, we determined what color we were currently looking at by comparing it to a baseline which was taken when the server was created. We couldn't just hard-code in the value of the baseline because it varied wildly from place to place depending on lighting/surfaces. 
If we use the baseline-comparison technique again, and you should feel free to come up with any other technique you think is better if you end up with a better idea, the baseline should be taken with a button press.

**Comment by AhmedSamara** [comment]
Color sensor has now been set up with watch_for_not_color as of 171a23257d1956f861c2e2d31f01792020bc7c56, which works.

**Comment by jasteve4** [comment]
A new issue needs to be created for this years bot once the rules have been finalized.
