### ISSUE TITLE
Creating a schematic for the bot

### ISSUE THREAD

**Issue by jakunesh** [IEEERobotics/bot2014#178]
A major problem we had last year was only a handful of people knowing where a wire went if it fell out. We are working hard to mitigate that risk this year through a combination of new wire management techniques and the Dark Power project.  However it is still helpful to have a document to reference the wireing layout including pins on the beagle bone to the various modules.

This needs to be done fore the Line Following dev-bot and the same thing needs to be created for the new bot as it is built.

This issues specifically pertains to creating the documents and beginning to layout the schematic

**Comment by jasteve4** [comment]
The wiki has been a great help.
