### ISSUE TITLE
X connector for open beam

### ISSUE THREAD

**Issue by R00ney** [IEEERobotics/bot2014#181]
ME guys,

with certain designs in the new bot construction, there are setups where 3 beams create an X crossing (one long diagonal, 2 short for the other diagonals). In this case, it would be usefull to have X shaped connectors  to be 3D printed.

I believe cad models for the other connectors can be found on open beam's website, so those can be a basis for modelling the new one.

**Comment by jasteve4** [comment]
The x shaped mount worked.
