### ISSUE TITLE
Torque Requirements for Etch-A-Sketch

### ISSUE THREAD

**Issue by whiteskulleton** [IEEERobotics/bot2014#182]
How much torque does it take to turn the Etch-A-Sketch knob?

Testing instructions:
Print the attached stl files:
Lever Arm
https://drive.google.com/a/ncsu.edu/file/d/0B8cZC9JtfQr6YUYzR3VHR3NDaFU/view?usp=sharing

Weight box:
https://drive.google.com/a/ncsu.edu/file/d/0B8cZC9JtfQr6ZHp6LUJSNkN4YkU/view?usp=sharing

 You are going to want to do like a 25% fill or so. That is just a guess for the fill but I wanted to keep the parts light so as not to interfere with the test. There should be a digital scale in locker 3. It comes with a plug and you will need that to weigh some objects for testing. Clamp down the etch-a-sketch into a vise in Troxler. Over by the black bookcases is a table with a vise that you can use to clamp the etch-a-sketch. Don't apply much force to the vise as you will break the etch a sketch if you do that. All you are trying to do is hold the etch-a-sketch. You can probably do this test without a vise but it might be easier if you just use the vise.
Anyway, setup the etch-a-sketch and the parts as shown in the picture. Measure the weight/mass of the box and the lever and write those weights down. The units you should be using are grams. You are going to need a 3 mm bolt and nut to assemble the pieces together after you weight the printed objects. Assemble the parts and place bolts and nuts or other random objects into the box until the knob turns a little. Weigh the entire assembly and write down the measurement in grams. Repeat the process at least 5 more times. It would be great if you could get 10 measurements though. Next, do the same exact thing for the other knob for a total of 10-20 measurements and write down your results on git hub.

![etch-a-sketch setup](https://cloud.githubusercontent.com/assets/5516069/4569429/0cac6698-4f4a-11e4-8edd-4231fa4ab896.png)
![etch-a-sketch setup 2](https://cloud.githubusercontent.com/assets/5516069/4569430/1021313c-4f4a-11e4-87ca-a253d248a1ae.png)

Note: the lever arm has a distance of 2 inches if you guys want to do the calculations but please write down your raw measurements on github. I don't know if the models are going to work the way that I planned but try and connect the 3d prints to the knobs using tape or other means if this model doesn't work out. Thank you.

**Comment by jakunesh** [comment]
This has moved on to more of a friction issue than a force issue
