### ISSUE TITLE
Create hardware abstraction for stepper motors.

### ISSUE THREAD

**Issue by AhmedSamara** [IEEERobotics/bot2014#195]
Related to #167.

We need a hardware abstraction for controlling stepper motors.

**Comment by AhmedSamara** [comment]
So the abstraction that @kvijay1995 works, but it is somewhat of a hack because it involves bit-banging.
@jasteve4 suggested an alternative that involves 2 PWM's instead of 4 GPIOS, that should also be more reliable.

**Comment by Kaduki** [comment]
We thought we would only need 2 PWM's but actually, we needed 3. Therefore, we had to design the circuit again from scratch. I made a circuit on breadboard to make a stepper motor work. It was done to reduce the work for CPU. Hopefully, it will make the motor move faster. Also, I coded an program in Arduino to make a signal with 3 different frequencies. LINK: https://gist.github.com/Kaduki/92497ebff680cd6defb2

**Comment by AhmedSamara** [comment]
Here is the schematic they built.
![stepper motor controller circuit.](https://lh3.googleusercontent.com/oaNYuKSVKuLiNjdByjd1qKaHQwK6t4eXvC6a197mN_RS3f7BjAsZ86HB1aFQqDAhVMJoXVeH_TI=w1342-h536)

It takes in 3 PWM signals as input, which unfortunately, is still fairly expensive for us. (The previous option was 4 GPIOS, and high processor usage because it involved bit banging).

We can use a clock divider IC to reduce the number of PWM's required.
I think [this](http://www.ti.com/product/CD4521B/samplebuy) is what we need , but samples are not currently available, at least not for me.(It just says to contact TI).

I'd appreciate it if someone could check the link to see if they can order a free sample.

**Comment by AhmedSamara** [comment]
This might be a good thing to work on after competition.

**Comment by jasteve4** [comment]
We plan to create a cape that will have the hardware to handle stepper motors. We should not need to bit bang the stepper motors.
