### ISSUE TITLE
Testing old motors

### ISSUE THREAD

**Issue by jakunesh** [IEEERobotics/bot2014#200]
Thanks to the effort of Josh we've got some old motors that are currently working and mounted on the New bot's chassis.

We need to test and see if these motors encoders are still working and if we can use them to move the bot, or if they will have to be limited to place holders until we can get new motors.

To test these motors you need to hook them up to power and monitor the encoder signal on a oscilloscope.  If this can be verified that would be a big win financially and a modest win in speeding up development time. 

This shouldn't be a very difficult task, assuming they aren't busted

**Comment by jasteve4** [comment]
The Old motors are working nicely on the CS Bot. There has been no issue with these motors as of yet.
