### ISSUE TITLE
Rubix's Cube Solution

### ISSUE THREAD

**Issue by cdyoder** [IEEERobotics/bot2014#213]
11/14/14

Progress on the Rubix's cube solver has been made as of Friday. The image below is the current solver iteration next to the current Simon solver. 

![20141114_200342](https://cloud.githubusercontent.com/assets/8527263/5056216/1825b930-6c45-11e4-92ca-3877621fc253.jpg)

The Rubix's solver needs a second solenoid on the top printed piece in order to properly hold the cube for rotation. See issue #212

**Comment by asatish127** [comment]
Flowchart for movement of the bot for the rubiks cube part of the competition:
Bot moves towards the cube---> Stops when the bot reaches the box(assume that the rubix cube is placed far enough into the box that the bot's gripper can reach it)---> Gripper closes and pushes cube into place for rotation(The rotator should be perpendicular to the side of the bot)---> The rotator turns 180 degrees---> Gripper opens---> bot moves sideways to the right dislodge cube and then moves backwards till all of the back IR's sense white.

**Comment by AhmedSamara** [comment]
I've begun working on the abstraction class for this.

The abstraction can already turn a servo, but hardware/motor.py was missing some information about how to use it. Specifically, it just mentioned a single GPIO pin being used.

Obviously it had to be connected to the H-bridge, but the wiring was not specified in the spec.

The H-bridge controller we had at our disposal was the L298N, which required two inputs.
http://tronixlabs.com/news/tutorial-l298n-dual-motor-controller-module-2a-and-arduino/

Once I get this working, I'll also update the motor.py documentation.

**Comment by AhmedSamara** [comment]
I finally found the exact part and not just a similar board that uses a similar chip!

https://solarbotics.com/product/k_cmd/
