### ISSUE TITLE
Modify beaglebone case

### ISSUE THREAD

**Issue by kvijay1995** [IEEERobotics/bot2014#221]
Locate the beaglebone case and if we don't have a solidworks file or IGES file, model the case. Once modeled, it has to extended/ modified a little bit. ***Make sure it fits with the IR array holder.***

**Comment by whiteskulleton** [comment]
I uploaded the case file to myhub and then exported it as a stp:
https://myhub.autodesk360.com/ue29cad18/docstore/permalink/DSabee1QT1a327cf2b7a72605e3a4071494e
It is located under Data>Files>CAD Files>BEAGLEBONE CASE-V1.stp

FYI: Whenever you export something from myhub it will automatically export to Data>Files>CAD Files. It will take a little bit of time to do so. Probably like 5-10 minutes I think. Then just go to that location and download the file. Also, if you make any changes go back to the same location and then:
Click the file>Actions>Upload New
to upload the changes.

**Comment by cdyoder** [comment]
Printed at mounted on the bot. Will need to be revised once the IR array is printed. Also needs to be adapted for the start sensor signal.

**Comment by jakunesh** [comment]
Beagle bone case is printed and mounted on the competition bot
