### ISSUE TITLE
Label Parts in locker

### ISSUE THREAD

**Issue by whiteskulleton** [IEEERobotics/bot2014#225]
We need to create a quick organization system and label everything where it goes so it is very easy to clean up and know where everything is.

**Comment by jakunesh** [comment]
Thanks to @PaladinEng for bringing in the labeling tool. At Hack Day tonight we can begin organizing and labeling

**Comment by jakunesh** [comment]
It took awhile, but we have everything organized and labeled! Let's make sure not to let everyone's effort go to waste and keep it neat
