### ISSUE TITLE
Wire final bot together.

### ISSUE THREAD

**Issue by AhmedSamara** [IEEERobotics/bot2014#233]
Power, encoders, etc

**Comment by jakunesh** [comment]
Sean and I are chugging away at this, the drive motors and the bone are now wired as well as some of the peripheral motors.  The logic connections to the bone will be done last

**Comment by jakunesh** [comment]
This task is complete, save for the things that plug into the logic pins of the bone, but since the connectors for those are all made we are ready to rock on Asembis!
