### ISSUE TITLE
What tools would the team like access to that we don't have access to now?

### ISSUE THREAD

**Issue by AhmedSamara** [IEEERobotics/bot2014#235]
Rodney, our possible new mentor for the team, has access to a lot of great tools that might be useful for the club. Please make a list of what tools we might need access to or borrow from him at times, so that he knows what he needs from us.

This mostly applies to the mechanical Engineers. @whiteskulleton @amarron314 @cdyoder @therestofyou

**Comment by whiteskulleton** [comment]
I need the flange of the timing belt pulley cut off with the lathe as well as some shafts to be cut up using a lathe.

**Comment by jakunesh** [comment]
I've just received and replied to an Email from Rodney inquiring about the things mentioned above.

Keep em coming!
