### ISSUE TITLE
Find better sensors for solving "simon says".

### ISSUE THREAD

**Issue by AhmedSamara** [IEEERobotics/bot2014#236]
Possibilities:

-Better microphone. (The current one is not sensitive enough to consistently detect the Simon noises).

-Photo-transistors. (For individually detecting the options).

**Comment by AhmedSamara** [comment]
I've stubbed out a solver for solving this problem and written code for reading from the GPIOs on this sensor.

**Comment by jasteve4** [comment]
At this point in time the light detection circuit is good enough to see all the lights on the Simon Says player.
