### ISSUE TITLE
TI parts that need to be ordered 

### ISSUE THREAD

**Issue by jasteve4** [IEEERobotics/bot2014#241]
He is a TI part that we need to be ordered. 

http://www.ti.com/product/ADS7830/samplebuy

If you do not have a TI account, make one. Order three free samples of the part in the link above. If you have ordered this part before, disregard this issue. Uses you own address.

**Comment by AhmedSamara** [comment]
@jasteve4 Do we need more?

**Comment by AhmedSamara** [comment]
Can anyone that hasn't already ordered a sample go ahead and order this?

**Comment by AhmedSamara** [comment]
I just ordered 5 more.

**Comment by jasteve4** [comment]
We should have enough of these parts now, we can reopen this issue if we need more parts.
