### ISSUE TITLE
Print Rail_Adjust_Left

### ISSUE THREAD

**Issue by whiteskulleton** [IEEERobotics/bot2014#245]
Need the Rail_Adjust_Left Printed. Please monitor it as it is a small part and it might jam the printer.
https://drive.google.com/a/ncsu.edu/?tab=wo#folders/0B93g4TjHMS2pZ0NubEFBTWxJZTA

![rail_adjust_left](https://cloud.githubusercontent.com/assets/5516069/5668799/71e06788-9740-11e4-9c9d-8300bbbd335f.png)

**Comment by jakunesh** [comment]
Today James and Alua printed out 2 beautiful copies of this. Placed on the
top shelf

**Comment by whiteskulleton** [comment]
Can I get another one of these printed up?

**Comment by jakunesh** [comment]
I just tried printing this in Troxler and I got some strange error in code, I'm going to see if the senior design TA's know what is going on

**Comment by jakunesh** [comment]
Printed out 2, they came out very well.

**Comment by whiteskulleton** [comment]
1. The set screw holes come out slightly too big. It is recommended that they be modeled smaller and then drilled to the correct size for tapping.
2. The part does not made the shaft rigid and allows it to flex some and it is recommended that the part be made more rigid.
