### ISSUE TITLE
Wrong dir for scripts

### ISSUE THREAD

**Issue by dfarrell07** [IEEERobotics/bot2014#247]
@jasteve4 commited a new top level directory for a USB-related [script](https://github.com/IEEERobotics/bot2014/blob/master/usb_connect/usb_connect.sh) a few weeks ago. It should be in `bot/scripts`.

**Comment by jasteve4** [comment]
Ok, Make sense.

I will make sure to keep the scrips in the scripts directory.

**Comment by AhmedSamara** [comment]
Moved scripts to correct directory.
