### ISSUE TITLE
Print Stepper Block

### ISSUE THREAD

**Issue by whiteskulleton** [IEEERobotics/bot2014#252]
I will need 2 of these stepper blocks printed. Print one for now then print the other objects and come back and print the second one.
https://drive.google.com/file/d/0B8cZC9JtfQr6c2NmeUJRbHNFRk0/view?usp=sharing
![stepper block](https://cloud.githubusercontent.com/assets/5516069/5749717/9d9a473a-9c19-11e4-948f-c76f665156f7.png)

**Comment by jasteve4** [comment]
done

**Comment by whiteskulleton** [comment]
I need another one of these printed

**Comment by cdyoder** [comment]
Currently being printed.

**Comment by cdyoder** [comment]
Printed. Decent quality (definitely usable). Placed in the cabinet in "Mark's Box".

**Comment by whiteskulleton** [comment]
Problems:
All the holes came out as ovals. This is bad because when some of the holes are tapped, there will be little thread engagement and they won't hold a screw properly. It is recommended that the holes be modeled smaller and then drilled out to get to the correct size.

The printed model came out to the correct size.
