### ISSUE TITLE
Testing the DC Motor for turning the Rubix Cube

### ISSUE THREAD

**Issue by cdyoder** [IEEERobotics/bot2014#260]
Currently, we have a DC motor with encoder mounted on the bot to turn the Rubix cube  top row. There is discussion of switching the motor to a stepper motor instead of the DC motor. Before we make the switch, I would like someone to write a basic code, using the Bone, to send a signal to the DC motor and see if we can reliably rotate the Rubix cube. 

Ideally, I would like this to be done from a Bone using the DC motor currently mounted to the bot. If you're interested, please talk with either myself or Ahmed.

**Comment by cdyoder** [comment]
@pvsteja 
@asatish127

**Comment by AhmedSamara** [comment]
The EE overview of what you'll need to do is:

-First see how accurately and consistently the motor can be moved using a power supply and just turning it on/off by hand.
-If that works well enough that it seems like it's even worth attempting, you can move to using GPIO pins (either on a Beaglebone or on an Arduino) to control a transistor that controls the supply of power to the motor.

**Comment by cdyoder** [comment]
Update:
The DC motor is able to turn the top row of the cube. Proven 1/20/15.

**Comment by jakunesh** [comment]
according to above comment:
"The DC motor is able to turn the top row of the cube. Proven 1/20/15."
this issue is closed. Using a micro controller to do this will be a separate issue, since that is basically solving the task
