### ISSUE TITLE
Block Level Diagram and Wiring Info for the Bot

### ISSUE THREAD

**Issue by SeanKetring** [IEEERobotics/bot2014#264]
We need a fully detailed wiring scheme for the bot's power system, and a block level diagram showing how everything fits together.  This issue can be closed after this info has been uploaded the wiki.

**Comment by SeanKetring** [comment]
![powersystem](https://cloud.githubusercontent.com/assets/7844136/5869750/165e2db2-a28c-11e4-9de0-0b08308ca39e.png)


Here is a crude illustration of the power system, more info to come later but so far there is a basic color scheme:

Black is going to always be ground, the color with black will be the higher line

Battery voltage feeding into D.P. will be blue/black and red/black for logic battery and motor battery

All motors used in the task actuators will be powered from D.P. using red/black 22 gauge wire

All servos powered by D.P. will be using a yellow/black color scheme

The beagle bone black will be powered using blue/black wire 

The ADC will be powered with Green/Black wire.

Still need a diagram illustrating the interface with D.P.

**Comment by SeanKetring** [comment]
Here a map for interfacing with Dark Power. 

![image](https://cloud.githubusercontent.com/assets/7844136/5931582/752cb4aa-a66d-11e4-8e33-40a10d98e300.png)

**Comment by SeanKetring** [comment]
Note, Dark Power has a direct connection to the capes, these wires are blue and black

**Comment by SeanKetring** [comment]
In the interest of keeping track of changes, beagle bone black is powered through a cable that's all black, and two wires, kind of like a wall wart.  

The servo may have to be powered by the logic battery, unless we can figure out a way to share one d.p. Output between two devices 

Still to do as of when I left today:

Split the battery connections from two two pairs of wire to four two pairs of wire

Figure out which order connect to logic wires on the drive motors, to the capes

Mount and wire the adc 
Make logic diagram, 
Wire logic

**Comment by SeanKetring** [comment]
![image](https://cloud.githubusercontent.com/assets/7844136/6138276/acea90ca-b14d-11e4-9cbc-a7fb8ea32b97.png)

A slightly more accurate block diagram

**Comment by SeanKetring** [comment]
![image](https://cloud.githubusercontent.com/assets/7844136/6138365/79a011a8-b14e-11e4-951b-8e44d1ee07b2.png)
 
Revised Dp guide

**Comment by SeanKetring** [comment]
![image](https://cloud.githubusercontent.com/assets/7844136/6138822/b53a24de-b152-11e4-8d52-44742fc9698a.png)

Simon says sensor board


![image](https://cloud.githubusercontent.com/assets/7844136/6138866/399b2f8e-b153-11e4-8447-ecc4c6085e69.png)

Stepper motor control board

**Comment by SeanKetring** [comment]
![image](https://cloud.githubusercontent.com/assets/7844136/6139001/c4522438-b154-11e4-95a2-084decda7690.png)

Updated version

**Comment by SeanKetring** [comment]
![image](https://cloud.githubusercontent.com/assets/7844136/6976248/df348da2-d974-11e4-8346-5bdefa3f27c3.png)

**Comment by jasteve4** [comment]
This has all been moved to a wiki
