### ISSUE TITLE
Create wiki for how to get Eagle Pro

### ISSUE THREAD

**Issue by jakunesh** [IEEERobotics/bot2014#265]
Now that I have the info on how to download professional eagle, I need to create a wiki page for that club members now and it in future can get a free professional version of Eagle Cad

**Comment by jakunesh** [comment]
Created and placed on the wiki. Sorry for all the spam!

**Comment by thinkl33t** [comment]
You do realise anyone on the internet can download your eagle license right?

**Comment by AhmedSamara** [comment]
Thanks for letting us know @thinkl33t , I changed the privacy settings back to group only.
