### ISSUE TITLE
Print Sensor Holder 2

### ISSUE THREAD

**Issue by cdyoder** [IEEERobotics/bot2014#267]
File is posted to the to print folder on the drive and can be found here:

https://drive.google.com/drive/#folders/0B_7IPKiQjuIZUUJlZHN6NWRGeDA/0B93g4TjHMS2pRHNoWXRqdmhjaVk/0B93g4TjHMS2pZ0NubEFBTWxJZTA

Print face is as shown:
![sensor holder print](https://cloud.githubusercontent.com/assets/8527263/5868921/f762f56c-a27e-11e4-846a-6293fd83323b.png)

**Comment by jasteve4** [comment]
done
