### ISSUE TITLE
Print Simon Servo Mount 4

### ISSUE THREAD

**Issue by cdyoder** [IEEERobotics/bot2014#268]
File is in the to print folder on the drive and can be found here:

https://drive.google.com/drive/#folders/0B_7IPKiQjuIZUUJlZHN6NWRGeDA/0B93g4TjHMS2pRHNoWXRqdmhjaVk/0B93g4TjHMS2pZ0NubEFBTWxJZTA

Print face is as shown below:
![simon servo mount print](https://cloud.githubusercontent.com/assets/8527263/5869215/77ab7cb8-a283-11e4-87b3-6a1b9ad134f2.png)

**Comment by jasteve4** [comment]
done
