### ISSUE TITLE
Print simon stepper holder 2

### ISSUE THREAD

**Issue by cdyoder** [IEEERobotics/bot2014#269]
File is located in the to print folder on the drive and can be found here:

https://drive.google.com/drive/#folders/0B_7IPKiQjuIZUUJlZHN6NWRGeDA/0B93g4TjHMS2pRHNoWXRqdmhjaVk/0B93g4TjHMS2pZ0NubEFBTWxJZTA

Print face can be seen below:
![stepper holder print](https://cloud.githubusercontent.com/assets/8527263/5869242/15637136-a284-11e4-8267-09d36b7227d2.png)

**Comment by jasteve4** [comment]
done
