### ISSUE TITLE
Course Creation Procedure

### ISSUE THREAD

**Issue by jdekler** [IEEERobotics/bot2014#270]
Currently we have a small jar of pinkish white paint and a larger can of Black primer. We have all the components for the course, however the border walls will have to be taken down. 

Procedure:
1. Remove LED lighting
2. Coat entire surface with black primer
3. Mark out start box and play boxes with tape and fill with white paint
4. lay out course in painter's tape specified by rules and paint white
5. Lay down finish line
6. Assemble

**Comment by SeanKetring** [comment]
will there be a time that you will be working on this?  I have access to
some power tools and painting supplies

On Fri, Jan 23, 2015 at 9:12 PM, jdekler <notifications@github.com> wrote:

> Reopened #270 <https://github.com/IEEERobotics/bot2014/issues/270>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IEEERobotics/bot2014/issues/270#event-224088538>.
>



-- 
Thank you, and have a good day!
Sean Ketring

Electrical Engineering Undergraduate

**Comment by psychomugs** [comment]
Removed the LEDs and painted the black base coat, currently waiting for it to dry.

Josh and Ahmed brought out a large, one-piece platform that is apparently better for testing line following. Painting that can take place another day when we get more black paint.

**Comment by cdyoder** [comment]
The final course (the course with walls) has been finished and approved for testing. The other course (two sheets of plywood) can also be used for testing if needed.

**Comment by jakunesh** [comment]
I believe @cdyoder last update qualifies as this issue being closed until proven otherwise
