### ISSUE TITLE
Print Fuse Holder

### ISSUE THREAD

**Issue by amarron314** [IEEERobotics/bot2014#273]
The fuse holder piece is ready to be 3d printed.
It is in https://drive.google.com/drive/#folders/0B_7IPKiQjuIZUUJlZHN6NWRGeDA/0B93g4TjHMS2pRHNoWXRqdmhjaVk/0B93g4TjHMS2pZ0NubEFBTWxJZTA
and named fuseHolder.stl

**Comment by jakunesh** [comment]
This is currently printing

**Comment by jakunesh** [comment]
Printed and placed in the current work box
