### ISSUE TITLE
Design of a wedge beam for the front rail

### ISSUE THREAD

**Issue by cdyoder** [IEEERobotics/bot2014#274]
The front most piece of open beam is twisting, causing the cantilevered Simon and Rubix's cube solutions to become misaligned. Design a 3D printed beam which is just the length of the span between the front most and second front most beams to reduce the twisting effect. The beam will need to be a wedge-type fit (close fit) with several holes to adapt to a T-style connector (commonly used for open beam connections).

**Comment by SeanKetring** [comment]
Done.
