### ISSUE TITLE
Order Parts for Dark Power from Ti

### ISSUE THREAD

**Issue by jasteve4** [IEEERobotics/bot2014#276]
Here is the link to the power module:

http://www.ti.com/product/PTN78020W/samplebuy

**Comment by jakunesh** [comment]
I'd recommend consolidating the parts we want to get sampled from TI under 1 issue for ease of ordering by our members

**Comment by jakunesh** [comment]
This part is no longer available for free sampling, this issue will remain closed unless that changes
