### ISSUE TITLE
Front IR array not working.

### ISSUE THREAD

**Issue by AhmedSamara** [IEEERobotics/bot2014#277]
The front IR arrays are constantly reading 255.

I yanked them out and tested them on an oscilloscope, and the output seemed to be normal otherwise.

**Comment by jakunesh** [comment]
Is it a problem with the ADC? I would try switching the cables around and seeing if the problem moves with the cables

**Comment by jasteve4** [comment]
I fixed it, there was a problem with the the Ir boards
