### ISSUE TITLE
Finish assigning BeagleBone black pins.

### ISSUE THREAD

**Issue by AhmedSamara** [IEEERobotics/bot2014#280]
Still to be assigned:

Signal | type | Suggested pin | notes
--------|--------|---------------|---------------|
Rubix cube gripper motor dir:  | GPIO | P9_30 (gpio3[16]) (k-112) | 
Rubix cube gripper power: | PWM | P9_29 (EHRPWM0B) | 
Simon says servo: | PWM | P9_21 (EHRPWM0A) | 
Etch-a-sketch stepper (left) | PWM | P9_14 (EHRPWM1A) | stepper motors previously required 4 GPIOS, but the new design by Josh lets us use one PWM.
Etch-a-sketch stepper (right) | PWM | P9_16 (EHRPWM1B) | (directly next to the other etch-sketch pwm. Easier wiring

All of these assignments were pretty much picked arbitrarily, but unless anyone (Particularly @jasteve4 ) has any assignments or designs/code with other assumptions or a reason to use ECAP PWM, over EHRPWM I'm going to go ahead and use these.

**Comment by AhmedSamara** [comment]
This has to change, the rubix gripper actually requires two GPIOs for controlling direction, and doesn't really need a PWM.

**Comment by jasteve4** [comment]
This issue can be closed, this years bot will not need gripper.
