### ISSUE TITLE
Sign up to attend SoutheastCon

### ISSUE THREAD

**Issue by jakunesh** [IEEERobotics/bot2014#290]
We need to get moving on who is going to SoutheastCon. I've already created a sheet for this below and sent out an email. Please fill this out in a timely manner.

https://docs.google.com/a/ncsu.edu/spreadsheets/d/1NMfbqIGODgMOcYEHx_OPKNPUuWU35waDXEwC5VM-XeQ/edit#gid=0

**Comment by whiteskulleton** [comment]
We also need to know what day and time we are leaving.

**Comment by jakunesh** [comment]
Last call for this. I want to send it out tomorrow. Some of you don't have your IEEE membership number included. Make sure to put that in ASAP, I plan to submit the names tomorrow

**Comment by jakunesh** [comment]
I've sent off the Roster for who is going to SEcon, I'll provide everybody updates as I get them.
