### ISSUE TITLE
I2c object for the i2c addressable pot 

### ISSUE THREAD

**Issue by jasteve4** [IEEERobotics/bot2014#293]
There needs to be an abstraction class created for the i2c addressable pot.

**Comment by AhmedSamara** [comment]
Using the i2cObject library is probably overkill, smbus should be more than enough.

What's the part number for the pot?

**Comment by jasteve4** [comment]
Have trouble with passing hex values form the cli client to the function set_pot_wiper.

**Comment by jasteve4** [comment]
Fixed it, must pass variables in as int. Hex values are treated as a string.

**Comment by jasteve4** [comment]
The Pot object is done and read for use. The find_ambient_light function can be used to set the pot to the current ambient light. More useful information can be found on the on the senors cape wiki.
 https://github.com/IEEERobotics/bot2014/wiki/Sensor-Cape
