### ISSUE TITLE
Update wiki with instructions on how to assign GPIO pins.

### ISSUE THREAD

**Issue by AhmedSamara** [IEEERobotics/bot2014#309]
The [BBB pins wiki](https://github.com/IEEERobotics/bot2014/wiki/BBB-Pins) has all of our assignments on a page.

It would be a good idea to update this with a detailed explanation of what all the various values (MC number, kernel #, etc) mean, and what considerations should be taken into account when assigning them. As discovered in #303, it's not as simple as just picking whatever you want.

Also, it would be nice if instead of a table we used a spreadsheet or something that corresponded to the physical layout so that it's easier to see where things plug in.

**Comment by jasteve4** [comment]
This is being move over to a wiki.
