### ISSUE TITLE
Hardware abstraction for simple motors

### ISSUE THREAD

**Issue by jasteve4** [IEEERobotics/bot2014#312]
There needs to be a hardware abstraction created for the motor H-bridges. Each H-bridge needs 4 GPIOs to control up to 2 motors. These GPIOs don't need to be attached to a PWM pins, because we are running the motors at full speed.

See issue on H-Bridges for details on the H-bridges.  
https://github.com/IEEERobotics/bot2014/issues/311

**Comment by kvijay1995** [comment]
I'm on this, if someone else is working on this please let me know.
