### ISSUE TITLE
Mount new motors onto Asembis

### ISSUE THREAD

**Issue by jakunesh** [IEEERobotics/bot2014#313]
The motors are now in, there was a mix up in the office. We now are ready to replace to motors on Asembis and test them to close this issue.

**Comment by whiteskulleton** [comment]
Just finished mounting the motors. I dremeled a dimple on each of the shafts and put loctite on each of the set screws. Now we just need to test the crap out of it.

**Comment by jakunesh** [comment]
Complete and working. Asembis moves waaaaaay better then I expected! Great stuff. Any future problems will be addressed in a new issue
