### ISSUE TITLE
Current state of the to buy list

### ISSUE THREAD

**Issue by jasteve4** [IEEERobotics/bot2014#314]
I could not find an issue about the current state of the "to buy list". So, this seem to be a good place to start this issue. 

I have added some parts form newark and pololu to the current order page on the to by list.

**Comment by jakunesh** [comment]
Here's the deal. Competition is right at 2 weeks away. Anuj thinks it will be fastest if we order the parts ourselves and then we can get reimbursed for them. 

Those willing go ahead and get the parts ordered to your homes and you will be reimbursed.

MAKE SURE YOU POST HERE THAT YOU ARE GOING TO BUY SOMETHING BEFORE YOU DO! We don't want any double orders

**Comment by AhmedSamara** [comment]
I'm about to send out the order from pololu for micro-motors and IR-arrays.

Is that all we need from them?

**Comment by AhmedSamara** [comment]
Order sent.

**Comment by AhmedSamara** [comment]
Ordered sdp as well.

**Comment by jakunesh** [comment]
I am making the purchase for the Newark parts now

**Comment by jakunesh** [comment]
All the parts that were on the To Buy list have now been ordered. This can be considered that last chance we had to order before SEcon, lets hope it actually comes in
