### ISSUE TITLE
External peripherals for testing and programming 

### ISSUE THREAD

**Issue by jasteve4** [IEEERobotics/bot2014#315]
At some point in time, we talked about add a led to indicate when the start signal is detected. We could add a rgb led instead. This would allow use to reflect many different states that we may want to know during testing. Also, It may be helpful to add some external switch so we can do some level of configuring without changing coding at the competition.

**Comment by AhmedSamara** [comment]
Instead of an RGB LED we might as well just use 3 LEDs.  It would take the
same number of GPIOs, and would be easier to read.

**Comment by jasteve4** [comment]
I have created a board the help with this. See #365 for more.
