### ISSUE TITLE
Print Micro Motor Mount

### ISSUE THREAD

**Issue by whiteskulleton** [IEEERobotics/bot2014#323]
Need 5 of these printed
https://drive.google.com/a/ncsu.edu/?tab=wo#folders/0B93g4TjHMS2pZ0NubEFBTWxJZTA

![micro motor mount](https://cloud.githubusercontent.com/assets/5516069/6766900/bae04290-cfef-11e4-85b5-45e94659ba69.png)

**Comment by jakunesh** [comment]
Have printed 5 of these that appear to work, will leave this open for another day in case we have time to print a couple extra for backup

**Comment by whiteskulleton** [comment]
Micro motor mount was not thick enough and the set screw holes were too small.

**Comment by jakunesh** [comment]
Didn't get to printing the back-ups, will do before SEcon if there is time
