### ISSUE TITLE
Print IR Spacer

### ISSUE THREAD

**Issue by whiteskulleton** [IEEERobotics/bot2014#326]
Will need 4 of these parts. Just print 1 and test to see if it is the right size before printing the rest.

https://drive.google.com/a/ncsu.edu/?tab=wo&urp=https://drive.google.com/?tab%3Dwo#folders/0B93g4TjHMS2pZ0NubEFBTWxJZTA

**Comment by jasteve4** [comment]
I printed 4 of them and moved it into the printed folder

**Comment by jakunesh** [comment]
They are on the bot and it seems to work quite well
