### ISSUE TITLE
Print Color Spacer

### ISSUE THREAD

**Issue by whiteskulleton** [IEEERobotics/bot2014#327]
https://drive.google.com/a/ncsu.edu/?tab=wo&urp=https://drive.google.com/?tab%3Dwo#folders/0B93g4TjHMS2pZ0NubEFBTWxJZTA

![color spacer](https://cloud.githubusercontent.com/assets/5516069/6855886/6b528fda-d3d2-11e4-96e8-d67ac8de122c.png)

**Comment by jakunesh** [comment]
We've made a couple attempts to re-print one of these but all the 3-d printers are very inconveniently down. Luckily this is a backup part at this point, since the one we have mounted on the bot now works
