### ISSUE TITLE
Print Color Base

### ISSUE THREAD

**Issue by whiteskulleton** [IEEERobotics/bot2014#328]
https://drive.google.com/a/ncsu.edu/?tab=wo&urp=https://drive.google.com/?tab%3Dwo#folders/0B93g4TjHMS2pZ0NubEFBTWxJZTA

![color base](https://cloud.githubusercontent.com/assets/5516069/6855903/80119f92-d3d2-11e4-86cc-77fee3c9f4ea.png)

**Comment by jasteve4** [comment]
Just got done printing this part, waiting to see if it will work. Moved it into the printed folder.

**Comment by jakunesh** [comment]
Color sensor mounted successfully!
