### ISSUE TITLE
Configure Simon says player abstraction to use new micro-motors.

### ISSUE THREAD

**Issue by AhmedSamara** [IEEERobotics/bot2014#330]
#311 is nearly complete, and now we need code to be able to control it.

I don't reccommend using the `motor.py` abstraction class right now, because it doesn't work in its current state, and there's also a large difference that it assumes that we're not using here. Mainly, no PWM is required. We just need the motor moving forward, backward, or stopped. Speed is irrelevant.

The basic operation is simple.   
When AIN1 is HIGH, so is A1OUT is also HIGH (but with motor supply instead of logic supply).

**Comment by kvijay1995** [comment]
Working on this as of now!

**Comment by jasteve4** [comment]
This will not be an issue due to the new motor cape.
