### ISSUE TITLE
List of things to bring on SEcon trip.

### ISSUE THREAD

**Issue by AhmedSamara** [IEEERobotics/bot2014#331]
Nothing is too obvious to list explicitly for check off. Don't trust our adrenaline fueled and sleep deprived brains of pre-SEcon to remember everything as we're packing up.

* Competition bot.   
* CS bot (incase of parts)   
* Electrical tape.  
* Duct tape.  
* Assorted tools.

**Comment by whiteskulleton** [comment]
Dremel
Wooden box

**Comment by jakunesh** [comment]
zip ties
extra wires
crimp gun
crimper
crimps
made wires
current work

**Comment by SeanKetring** [comment]
CS (Ahmed's) Laptop
All cables for beagle bone
Hand held meter
Stuff for charging the batteries


On Tue, Mar 31, 2015 at 10:16 PM, Ahmed Samara <notifications@github.com>
wrote:

> Nothing is too obvious to list explicitly for check off. Don't trust our
> adrenaline fueled and sleep deprived brains of pre-SEcon to remember
> everything as we're packing up.
>
>    - Competition bot.
>     - CS bot (incase of parts)
>     - Electrical tape.
>     - Duct tape.
>     - Assorted tools.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IEEERobotics/bot2014/issues/331>.
>



-- 
Thank you, and have a good day!
Sean Ketring

Electrical Engineering Undergraduate

**Comment by jakunesh** [comment]
GPS
Soldering Iron and Solder
snacks
back up regulators
spare IR arrays
spare stepper motors and controllers

**Comment by AhmedSamara** [comment]
* Phone chargers.  
* (If anyone has a car adapter please bring it)
