### ISSUE TITLE
SouthEastcon cancelled.

### ISSUE THREAD

**Issue by AhmedSamara** [IEEERobotics/bot2014#335]
From the [Official facebook page](https://www.facebook.com/groups/1453294644905271/1623791801188887/?notif_t=group_activity)

>Due to the lack of registrations filled out by a majority of schools, the hardware competition has been cancelled for this year's SoutheastCon. We apologize for any inconvenience this may have caused.

Oh well, we had a good run everyone, we'll get them next year. I've already begun scrapping the bot in preparation for the next one.

**Comment by dfarrell07** [comment]
roflmao

**Comment by AhmedSamara** [comment]
You've all probably figured it out by now, but this was just an April fools day joke.
