### ISSUE TITLE
'[Errno 1] Operation not permitted'

### ISSUE THREAD

**Issue by ChadZhongqiangChen** [IEEERobotics/bot2014#336]
When I started the server on the bot and called a command, the following error came up.

ctrl_server.py | call_method | 264 | WARNING | Exception: '[Errno 1] Operation not permitted'
--> {'msg': "Exception: '[Errno 1] Operation not permitted'", 'type': 'error'}

**Comment by dfarrell07** [comment]
Are you running as root?

**Comment by AhmedSamara** [comment]
I think this may have been because of  the GPIO being set as an input in `stepper_motor.py`

**Comment by AhmedSamara** [comment]
Yup, it was. The stepper motors can no turn.
