### ISSUE TITLE
Wheels coming off of the bot

### ISSUE THREAD

**Issue by SeanKetring** [IEEERobotics/bot2014#338]
The vibrations of the bot moving around has shaken loose a couple of the drive motors.  We've managed to get them reattached but a mechanical person should look at this at some point.

**Comment by jakunesh** [comment]
@jdekler put dimples on the shafts that were falling off the bot, and worked to help strengthen the rigidity of the motor mounts.  Hopefully this will be a permanent solution to this issue that gets around the need to glue.
