### ISSUE TITLE
Grabbing Rubics cube

### ISSUE THREAD

**Issue by jakunesh** [IEEERobotics/bot2014#340]
In testing today we were using the servo to move the rubics cube successfully (yay!) but in using the power screw to bring in the rubics cube we had some issues where there was not enough room for error to successfully grab the cube without jamming.

This requires further testing and posibly some changes to the cube manipulator

**Comment by whiteskulleton** [comment]
I think we need to take the red pads off the gripper.

**Comment by AhmedSamara** [comment]
Everything worked, the robot was awesome, we won the competition and have been nominated for a nobel prize.
