### ISSUE TITLE
Change the Device Tree Overlay

### ISSUE THREAD

**Issue by jakunesh** [IEEERobotics/bot2014#343]
If we want to be able to control the micro motors in their current configuration we needs to change the device tree overlay to fix the mode of the pins so that we can use them effectively.

**Comment by jasteve4** [comment]
I am done with the device tree overlay, but I am having problems with loading the overlay from boot. i think  the overlay needs to be added to the setup_all.sh script. Not sure how to add overlay to the script.

Also, some of the pins are conflicting with HDMI. So, these pins are not loading. I recommenced using pins P8-7 through P8-19. I think I can get these to load.

Need to check to see that we are not conflicting with any other overlays that we are using in the setup_all script.

This video from youtube has been a great help.
https://www.youtube.com/watch?v=wui_wU1AeQc
