### ISSUE TITLE
missing key

### ISSUE THREAD

**Issue by jasteve4** [IEEERobotics/bot2014#347]
The key for the cabinet is not in the locker, does anyone know where the key is?

**Comment by jakunesh** [comment]
I had left it with @PaladinEng on Thursday. That is the last time I know it was seen

**Comment by PaladinEng** [comment]
I have it hidden in the bag by my workbench, because I forgot the locker
combo and was too lazy and tired to look it up.

**Comment by whiteskulleton** [comment]
Retrieved the key and placed it in the locker
