### ISSUE TITLE
Battery Management. 

### ISSUE THREAD

**Issue by jasteve4** [IEEERobotics/bot2014#361]
Today in the lab, there was a fire on the bot. A loose usb cable short out on the switch/fuse holder. The short damaged the usb hub and possible the wifi niks. The bone seems to be fine. Need to test to be sure.

As a rule of thumb, the batteries should be disconnected from the bot before it is put in the locker. 

Also, we should try to minimize the number of exposed electrical hardware and loose cables to prevent this from happening in the future. ie (Fuse holder, power switch, usb cable)

**Comment by SeanKetring** [comment]
Hazard noted on the wiki
