### ISSUE TITLE
Need PID constants to use with DMCC

### ISSUE THREAD

**Issue by jschornick** [IEEERobotics/bot2014#91]
If we're planning to effectively use the PID functionality of the DMCCs, someone needs to work out a reasonable set of constants for our motors.

The sample documentation from Exadler was using Kp, Ki, Kd of (-5278, -200, -500), which is a reasonable start for position targeting on my 34:1 2A test motor.

Velocity is another story entirely, and I can't find any combination that tracks a static velocity target.  Even maximizing the magnitude of the integral term never minimizes the error.  

Sample Python code to set and test PID values is in our fork of the DMCC library:
https://github.com/NCSUhardware/DMCC_Library/tree/master/pyDMCC/examples

**Comment by AhmedSamara** [comment]
I'm not sue if this one is still relevant anymore.
